# Generated by Django 4.0.6 on 2022-07-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='symbol',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
