# Generated by Django 4.0.6 on 2022-07-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0011_category_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(default='', max_length=2, unique=True, verbose_name='category_code'),
        ),
    ]
