# Generated by Django 4.0.4 on 2022-07-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0014_rename_joined_data_seller_joined_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='time_created',
            new_name='time',
        ),
    ]
