# Generated by Django 4.0.6 on 2022-08-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0016_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
