# Generated by Django 4.0.6 on 2022-08-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_chat_buyer_remove_chat_item_chat_user1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user1_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='user2_updated',
            field=models.BooleanField(default=False),
        ),
    ]
