# Generated by Django 4.0.6 on 2022-07-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_alter_category_id'),
        ('catalog', '0005_chat_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='seller',
        ),
        migrations.AlterField(
            model_name='chat',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='myshop.item'),
        ),
    ]
