# Generated by Django 4.0.6 on 2022-07-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_chatcontent_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcontent',
            name='content',
            field=models.CharField(default='', max_length=256),
        ),
    ]
