# Generated by Django 4.0.6 on 2022-07-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_chatcontent_content'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='chat',
            managers=[
            ],
        ),
    ]
