# Generated by Django 4.0.6 on 2022-07-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_chat_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrdered',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
