# Generated by Django 4.0.6 on 2022-07-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_itemordered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemordered',
            options={'verbose_name_plural': 'Items Ordered'},
        ),
    ]
