# Generated by Django 4.0.6 on 2022-07-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_itemordered_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatcontent',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chatcontent',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatContent',
        ),
    ]
