# Generated by Django 4.0.6 on 2022-07-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('T4', 'Banned User'), ('T3', 'Standard User'), ('T2', 'Member User'), ('T1', 'Administrator')], default='T4', max_length=2),
        ),
    ]
