# Generated by Django 4.0.6 on 2022-07-11 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='tier',
        ),
    ]
