# Generated by Django 4.0.6 on 2022-07-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0003_rename_type_user_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('T4', 'Banned User'), ('T3', 'Standard User'), ('T2', 'Member User'), ('T1', 'Administrator')], default='T3', max_length=2),
        ),
    ]
