# Generated by Django 4.0.6 on 2022-07-11 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sso.models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0004_alter_user_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('markdown', sso.models.NonStrippingTextField()),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
