# Generated by Django 4.0.6 on 2022-07-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0005_adminpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpost',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
