# Generated by Django 4.0.6 on 2022-07-12 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0007_alter_adminpost_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpost',
            options={'verbose_name_plural': 'Admin Posts'},
        ),
    ]
